const exception = _Exception();

class _Exception {
  const _Exception();
}
